### ISSUE TITLE
TypeError when attempting to build with v2.0.0

### ISSUE THREAD

**Issue by bkuri** [brunch/jade-brunch#28]
I'm getting the following error when attempting to build using `jade-brunch` v2.0.0:

```sh
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received false
  at assertPath (path.js:8:11)
  at Object.posix.join (path.js:479:5)
  at relativeToRoot (/usr/lib/node_modules/brunch/lib/deppack.js:50:55)
  at /usr/lib/node_modules/brunch/lib/deppack.js:65:40
  at Array.reduce (native)
  at Object.keys.filter.reduce (/usr/lib/node_modules/brunch/lib/deppack.js:63:53)
  at getNewHeader (/usr/lib/node_modules/brunch/lib/deppack.js:86:17)
  at generateModule (/usr/lib/node_modules/brunch/lib/deppack.js:102:10)
  at /usr/lib/node_modules/brunch/lib/deppack.js:151:13
  at tryToString (fs.js:414:3)
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

I attempted to reinstall using `npm install --save-dev jade-brunch@latest` as per the comment in #23, but the error remained. Not sure as to what else to try.

package.json:
```json
{
  "author": "@bkuri",
  "dependencies": {},
  "description": "",
  "devDependencies": {
    "auto-reload-brunch": "^2.0.0",
    "clean-css-brunch": "^2.0.0",
    "coffee-script-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "jade-brunch": "^2.0.0",
    "javascript-brunch": "^2.0.0",
    "stylus-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.1"
  },
  "engines": {
    "node": "latest"
  },
  "homepage": "",
  "keywords": [
    "brunch",
    "skeleton",
    "coffeescript",
    "jade",
    "stylus",
    "vuejs"
  ],
  "license": "MIT",
  "main": "index.coffee",
  "name": "vue-brunch",
  "repository": {
    "type": "git",
    "url": ""
  },
  "scripts": {
    "start": "brunch w -s",
    "test": "brunch test"
  },
  "version": "0.1.0"
}
```

brunch-config.coffee:
```coffee
exports.config =
  files:
    javascripts:
      joinTo:
        'js/app.js': /^app/
        'js/vendor.js': /^vendor/
        'test/js/test.js': /^test(\/|\\)(?!vendor)/
        'test/js/test-vendor.js': /^test(\/|\\)(?=vendor)/

      order:
        before: []

    stylesheets:
      joinTo:
        'css/app.css': /^app/
        'css/vendor.css': /^vendor/
        'test/css/test.css': /^test/

        order:
          after: []
          before: []

    templates:
      joinTo: 'js/templates.js'


  modules:
    nameCleaner: (path) ->
      path = path.replace(/^app\//, '')
      path = path.replace(/^javascripts\//, '')


  npm:
    enabled: yes


  plugins:
    static_jade:
      extension: '.static.jade'

    stylus:
      paths: [ './app/assets/css' ]
```

**Comment by goshakkk** [comment]
@bkuri which version of Brunch are you using? Can you try the latest? If that doesn't help, can you try with master `npm install brunch/brunch`?

**Comment by bkuri** [comment]
@goshakkk I was using version 2.1.3. I just updated to 2.2.3 and the TypeError went away. Thanks for the heads up. :+1:
